server:
  port: 8888
spring:
  application:
    name: cloud-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/omeraltan/microservice-config-server.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "omeraltan"
          password: ${GIT_KEY}

